# Generated by Django 6.0.4 on 2026-05-17 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventvendor_invited_email_alter_eventvendor_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_video',
            field=models.FileField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
