# Generated by Django 6.0.4 on 2026-05-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_banner_video_event_max_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
