# Generated by Django 6.0.4 on 2026-05-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='banner_portrait',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
    ]
