# Generated by Django 6.0.4 on 2026-05-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_banner_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='state_or_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
