# Generated by Django 6.0.4 on 2026-05-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_country_event_state_or_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvendor',
            name='invited_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
