# Generated by Django 6.0.4 on 2026-05-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventvendor_invited_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badge_template',
            field=models.TextField(blank=True, help_text='Custom HTML template for the badge. Use {fullname}, {ticket_id}, {ticket_type}, {qr_code} as placeholders.', null=True),
        ),
    ]
