# Generated by Django 6.0.4 on 2026-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_badge_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvendor',
            name='invited_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
