# Generated by Django 6.0.4 on 2026-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventvendor_invited_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvendor',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
