# Generated by Django 6.0.4 on 2026-05-27 15:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventvendor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvendor',
            name='media_public_showcase_allowed',
            field=models.BooleanField(default=False, help_text='If true, the vendor can showcase media from this event on their public portfolio.'),
        ),
        migrations.CreateModel(
            name='InvitedEventMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_image', models.ImageField(upload_to='invited_media/raw/')),
                ('watermarked_image', models.ImageField(blank=True, null=True, upload_to='invited_media/watermarked/')),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to='events.eventvendor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
