# Generated by Django 6.0.4 on 2026-05-29 22:38

import events.models.vendor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventvendor_media_public_showcase_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvendor',
            name='invitation_code',
            field=models.CharField(default=events.models.vendor.generate_invitation_code, editable=False, max_length=50, unique=True),
        ),
    ]
