# Generated by Django 6.0.4 on 2026-05-31 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventvendor_invitation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvendor',
            name='role',
            field=models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('VIDEOGRAPHER', 'Videographer'), ('PLANNER', 'Planner'), ('CATERER', 'Caterer'), ('DECORATOR', 'Decorator')], default='PHOTOGRAPHER', max_length=50),
        ),
    ]
