# Generated by Django 6.0.4 on 2026-06-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_eventvendor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_portrait',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='event_banners/'),
        ),
    ]
