# Generated by Django 6.0.4 on 2026-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_event_banner_image_alter_event_banner_portrait_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
