# Generated by Django 6.0.4 on 2026-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_attendees_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public_gallery_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
