# Generated by Django 6.0.4 on 2026-07-24 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_vendorrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('DROPDOWN', 'Dropdown'), ('CHECKBOX', 'Checkbox')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, help_text='List of options for DROPDOWN or CHECKBOX', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
