# Generated by Django 6.0.4 on 2026-07-24 01:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_customquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('recipient_type', models.CharField(choices=[('ALL', 'All Attendees'), ('CONFIRMED', 'Confirmed Only'), ('CHECKED_IN', 'Checked In Only')], default='ALL', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='events.event')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
