[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
norecursedirs = venv *migrations*
addopts = --nomigrations --ignore=test_api.py --ignore=test_serializer.py --ignore=test_user_serializer.py --ignore=test_users.py --ignore=tests/test_auth.py --ignore=tests/test_script.py --ignore=tests/test_serializer.py
