from abc import ABC, abstractmethod

class PaymentProvider(ABC):
    @abstractmethod
    def initialize_payment(self, amount: float, email: str, reference: str, **kwargs) -> dict:
        """
        Initializes a payment transaction with the gateway.
        
        Args:
            amount: The amount to charge (in base currency, e.g., NGN).
            email: Customer email address.
            reference: Unique transaction reference.
            
        Returns:
            dict containing:
                - 'authorization_url': URL to redirect the user for payment.
                - 'reference': The transaction reference (could be generated by gateway or returned as is).
        """
        pass

    @abstractmethod
    def verify_payment(self, reference: str) -> dict:
        """
        Verifies a payment transaction with the gateway.
        
        Args:
            reference: The transaction reference to verify.
            
        Returns:
            dict containing:
                - 'status': 'success', 'failed', or 'pending'
                - 'amount': The verified amount paid
                - 'currency': The currency of payment
                - 'raw_data': Original response data from the gateway
        """
        pass
