# Generated by Django 6.0.4 on 2026-05-12 09:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Event Owner'), ('VENDOR', 'Vendor'), ('ATTENDEE', 'Attendee')], db_index=True, default='ATTENDEE', max_length=20)),
                ('admin_subtype', models.CharField(blank=True, choices=[('OPS', 'Operations'), ('CUSTOMER', 'Customer Support')], max_length=20, null=True)),
                ('onboarding_status', models.CharField(choices=[('PENDING_EMAIL', 'Pending Email Verification'), ('PROFILE_INCOMPLETE', 'Profile Incomplete'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING_EMAIL', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_code', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('reference_image', models.ImageField(blank=True, help_text='For facial recognition entry.', null=True, upload_to='attendee_references/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventOwnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_account_ref', models.CharField(blank=True, help_text='Tokenised reference from the payment gateway.', max_length=255)),
                ('organisation_name', models.CharField(blank=True, max_length=255)),
                ('organisation_website', models.URLField(blank=True, max_length=255)),
                ('organisation_logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('is_business_verified', models.BooleanField(default=False)),
                ('total_events_created', models.PositiveIntegerField(default=0)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_account_ref', models.CharField(blank=True, help_text='Tokenised reference from the payment gateway.', max_length=255)),
                ('subtype', models.CharField(choices=[('PHOTOGRAPHER', 'Photographer'), ('PLANNER', 'Event Planner'), ('VIDEOGRAPHER', 'Videographer')], max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='vendor_profiles/')),
                ('service_title', models.CharField(blank=True, max_length=255)),
                ('service_areas', models.CharField(blank=True, help_text='Comma-separated list of locations served.', max_length=255, null=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('is_available_for_hire', models.BooleanField(default=True)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_unit', models.CharField(default='per_event', max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
