# Generated by Django 6.0.4 on 2026-05-12 09:52

import accounts.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.user.CustomUserManager()),
            ],
        ),
    ]
