# Generated by Django 6.0.4 on 2026-05-17 16:28

import core.utils.codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='registration_code',
            field=models.CharField(default=core.utils.codes.generate_registration_code, max_length=100, unique=True),
        ),
    ]
