# Generated by Django 6.0.4 on 2026-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_validatorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='subtype',
            field=models.CharField(max_length=50),
        ),
    ]
