# Generated by Django 6.0.4 on 2026-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendorprofile_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='cac_number',
            field=models.CharField(blank=True, help_text='Corporate Affairs Commission Registration Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_cac_verified',
            field=models.BooleanField(default=False),
        ),
    ]
