"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import uuid
from django.db import models
from pathlib import Path
from datetime import timedelta
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^-mnk2$+t6=)n#hv*e19n=#i!pu$hu2g%&%d&nxob8td9d5*0$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# custom user
AUTH_USER_MODEL = "accounts.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party
    'corsheaders',
    'rest_framework',
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",   # enables logout blacklisting
    "drf_spectacular",

    # Internal
    'accounts',
    'events',
    'tickets',
    'vendors',
    'photos',
    'payments',
    'notifications',
]

AUTH_USER_MODEL = 'accounts.User'   # or wherever your User model lives

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.SessionAuthentication',
    #     'rest_framework.authentication.BasicAuthentication',
    # ],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",

    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,

    # throttling for registration and login endpoints
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],

    "DEFAULT_THROTTLE_RATES": {
        # Global defaults (Highly generous for seamless local testing and high-traffic browsing)
        "anon": "5000/hour",
        "user": "50000/hour",
        "login": "100/minute",
        "owner_register": "100/hour",
        "vendor_register": "100/hour",
        "attendee_register": "500/hour",
    },
    
    "EXCEPTION_HANDLER": "core.exceptions.custom_exception_handler"
}


# ── Simple JWT ─────────────────────────────────
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "TOKEN_OBTAIN_SERIALIZER": "accounts.serializers.MyTokenObtainPairSerializer",
    "AUTH_HEADER_TYPES": ("Bearer",),
}
 
# ── drf-spectacular (API docs) ────────────────────────────────────────────────
SPECTACULAR_SETTINGS = {
    "TITLE": "NeoEvent API",
    "DESCRIPTION": (
        "AI-powered event ecosystem — Event Lifecycle · Ticketing · "
        "Attendance Validation · Media · Personalisation"
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,      # separates request/response schemas
    "TAGS": [
        {"name": "Authentication", "description": "Register, login, logout, token refresh"},
        {"name": "Profile", "description": "Authenticated user profile management"},
        {"name": "Admin – User Management", "description": "Internal admin: list, detail, approve users"},
    ],
    'ENUM_NAME_OVERRIDES': {
        'EventStatusEnum': 'events.models.Event.Status', 
        'RegistrationStatusEnum': 'tickets.models.EventRegistration.Status',
        'VendorRoleEnum': 'events.models.EventVendor.VendorRole',
    },
}

# replace with UUID 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# DEFAULT_PK_FIELD = "core.fields.UUIDPrimaryKeyField"

# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Postgresql local
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='neoE_db'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='iyanupy0007'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Auth Cookie  
AUTH_COOKIE = "refresh_token"
AUTH_COOKIE_SECURE = False  # True in production
AUTH_COOKIE_HTTP_ONLY = True
AUTH_COOKIE_SAMESITE = "Lax"
AUTH_COOKIE_PATH = "/"


# ── Email Settings (Resend SMTP Configuration) ───────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.resend.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'resend'
EMAIL_HOST_PASSWORD = config('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', 'NeoEvent <onboarding@resend.dev>')
SUPPORT_EMAIL = config('SUPPORT_EMAIL', 'support@neoevents.com')

# ── Payment Settings ────────────────────────────────────────────────────────
PAYMENT_GATEWAY = config('PAYMENT_GATEWAY', 'paystack')
PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY', '')

# ── Storage Configuration ──────────────────────────────
USE_S3 = config("USE_S3", default=True, cast=bool)

if USE_S3:
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID", default="")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY", default="")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME", default="")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-1")
    
    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    AWS_S3_FILE_OVERWRITE = False
    
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
else:
    # Use Local Storage for Development
    DEFAULT_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
    AWS_STORAGE_BUCKET_NAME = "local-media-bucket"
    AWS_S3_REGION_NAME = "local"


# ── SQS Background Tasks Configuration ─────────────────
USE_SQS = config("USE_SQS", default=False, cast=bool)
AWS_SQS_QUEUE_URL = config("AWS_SQS_QUEUE_URL", default="")

# ── Frontend Integration ───────────────────────────────
FRONTEND_URL = config("FRONTEND_URL", default="http://localhost:5173")

