# Generated by Django 6.0.4 on 2026-05-16 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventvendor_invited_email_alter_eventvendor_vendor'),
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventphoto',
            name='detected_users',
            field=models.ManyToManyField(blank=True, related_name='detected_in_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AttendeeGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_galleries', to='events.event')),
                ('photo_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_saves', to='photos.eventphoto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_event_gallery', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'photo_link')},
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embedding', models.BinaryField()),
                ('face_index', models.IntegerField(default=0)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='photos.eventphoto')),
            ],
            options={
                'indexes': [models.Index(fields=['photo'], name='photos_face_photo_i_7fd7eb_idx')],
            },
        ),
    ]
