# Generated by Django 6.0.4 on 2026-05-30 21:26

import django.db.models.deletion
import pgvector.django
import photos.models.photo
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventvendor_invitation_code'),
        ('photos', '0002_eventphoto_detected_users_attendeegallery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_file', models.ImageField(upload_to=photos.models.photo.event_gallery_upload_path)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=True)),
                ('ai_status', models.CharField(choices=[('PENDING', 'Pending AI Detection'), ('FACES_DETECTED', 'Faces Detected'), ('MAPPED_TO_USERS', 'Mapped to Users'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_embedding', pgvector.django.VectorField(dimensions=512)),
                ('bounding_box', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('source', models.CharField(default='AI', max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attendeegallery',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendeegallery',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendeegallery',
            name='photo_link',
        ),
        migrations.RemoveField(
            model_name='attendeegallery',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='eventphoto',
            name='photos_even_event_i_964072_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventphoto',
            name='photos_even_uploade_b27e97_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventphoto',
            name='photos_even_created_70e875_idx',
        ),
        migrations.RemoveIndex(
            model_name='faceembedding',
            name='photos_face_photo_i_7fd7eb_idx',
        ),
        migrations.AddField(
            model_name='photo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_event_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photoface',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_galleries', to='events.event'),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_users', to='photos.photo'),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_event_gallery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AttendeeGallery',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='detected_users',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='faceembedding',
            name='photo',
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['event'], name='photos_phot_event_i_e40660_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['uploader'], name='photos_phot_uploade_035c81_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['ai_status'], name='photos_phot_ai_stat_1bf010_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['created_at'], name='photos_phot_created_84134a_idx'),
        ),
        migrations.AddIndex(
            model_name='photoface',
            index=models.Index(fields=['photo'], name='photos_phot_photo_i_bbc063_idx'),
        ),
        migrations.AddIndex(
            model_name='userphoto',
            index=models.Index(fields=['user', 'event'], name='photos_user_user_id_3dca45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userphoto',
            unique_together={('user', 'photo')},
        ),
        migrations.DeleteModel(
            name='EventPhoto',
        ),
        migrations.DeleteModel(
            name='FaceEmbedding',
        ),
    ]
