# Generated by Django 6.0.4 on 2026-06-29 08:50

import photos.models.photo
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_photoface_userphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='raw_media_file',
            field=models.ImageField(blank=True, null=True, upload_to=photos.models.photo.event_gallery_upload_path),
        ),
    ]
