# Generated by Django 6.0.4 on 2026-05-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorgalleryevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorgalleryevent',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorgalleryevent',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
