# Generated by Django 6.0.4 on 2026-05-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorgalleryevent_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendorgallerycategory',
            unique_together={('vendor', 'name')},
        ),
    ]
