# Generated by Django 6.0.4 on 2026-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorgallerycategory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbusiness',
            name='custom_url',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
