# Generated by Django 6.0.4 on 2026-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorbusiness_custom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorgallerycategory',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_categories/'),
        ),
    ]
