# Generated by Django 6.0.4 on 2026-05-17 16:28

import core.utils.codes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_eventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_code',
            field=models.CharField(default=core.utils.codes.generate_registration_code, editable=False, max_length=50, unique=True),
        ),
    ]
