# Generated by Django 6.0.4 on 2026-05-23 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_dailycheckin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
