# Generated by Django 6.0.4 on 2026-05-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_fix_daily_checkin_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='badge_print_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='last_badge_printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
