# Generated by Django 6.0.4 on 2026-06-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_eventregistration_badge_print_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='ai_consent',
            field=models.BooleanField(default=False),
        ),
    ]
