# Generated by Django 6.0.4 on 2026-07-24 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_customquestion'),
        ('tickets', '0008_eventregistration_final_amount_paid_promocode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.JSONField(help_text='Stores the selected answer or text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='events.customquestion')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tickets.eventregistration')),
            ],
            options={
                'unique_together': {('registration', 'question')},
            },
        ),
    ]
