from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.conf import settings

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework_simplejwt.tokens import RefreshToken

from drf_spectacular.utils import extend_schema, OpenApiResponse, OpenApiExample

from ..models import User
from ..utils.emails import send_password_reset_email
from ..serializers.password import (
    PasswordResetRequestSerializer,
    PasswordResetConfirmSerializer,
    PasswordChangeSerializer,
)


# ─────────────────────────────────────────────────────────────────────────────
# Forgot-password — Step 1: request reset link
# ─────────────────────────────────────────────────────────────────────────────

@extend_schema(tags=["Password"])
class PasswordResetRequestView(APIView):
    """
    Submit an email address to receive a password-reset link.

    **Security note:** Always returns HTTP 200 regardless of whether the email
    exists in the system, preventing user-enumeration attacks.

    The reset link sent to the user's inbox contains a base64-encoded UID and a
    signed token generated by Django's `PasswordResetTokenGenerator`. The token
    is valid for `PASSWORD_RESET_TIMEOUT` seconds (default: 1 hour).
    """

    permission_classes = (AllowAny,)
    serializer_class = PasswordResetRequestSerializer

    @extend_schema(
        request=PasswordResetRequestSerializer,
        responses={
            200: OpenApiResponse(
                description="If the email is registered, a reset link has been sent.",
                examples=[
                    OpenApiExample(
                        "Success",
                        value={"detail": "If this email is registered, a reset link has been sent."},
                    )
                ],
            )
        },
    )
    def post(self, request):
        serializer = PasswordResetRequestSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        email = serializer.validated_data["email"]

        # Always return the same response — look up silently
        try:
            user = User.objects.get(email=email, is_active=True)
        except User.DoesNotExist:
            # Return 200 anyway — don't reveal whether email exists
            return Response(
                {"detail": "If this email is registered, a reset link has been sent."},
                status=status.HTTP_200_OK,
            )

        # Build the reset URL
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = PasswordResetTokenGenerator().make_token(user)

        # FRONTEND_URL should be set in settings, e.g. "https://app.neoevent.com"
        frontend_url = getattr(settings, "FRONTEND_URL", "http://localhost:3000")
        reset_link = f"{frontend_url}/reset-password?uid={uid}&token={token}"

        send_password_reset_email(user, reset_link)

        return Response(
            {"detail": "If this email is registered, a reset link has been sent."},
            status=status.HTTP_200_OK,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Forgot-password — Step 2: confirm token + set new password
# ─────────────────────────────────────────────────────────────────────────────

@extend_schema(tags=["Password"])
class PasswordResetConfirmView(APIView):
    """
    Complete the password-reset flow.

    Submit the `uid` and `token` from the reset link along with
    `new_password` and `new_password_confirm`.

    On success the user's password is updated and a fresh JWT pair is returned
    so the frontend can log them in immediately without a separate login call.
    """

    permission_classes = (AllowAny,)
    serializer_class = PasswordResetConfirmSerializer

    @extend_schema(
        request=PasswordResetConfirmSerializer,
        responses={
            200: OpenApiResponse(
                description="Password reset successful. Returns a new JWT pair.",
                examples=[
                    OpenApiExample(
                        "Success",
                        value={
                            "detail": "Password has been reset successfully.",
                            "access": "<jwt-access-token>",
                            "refresh": "<jwt-refresh-token>",
                        },
                    )
                ],
            ),
            400: OpenApiResponse(description="Invalid or expired token / passwords don't match."),
        },
    )
    def post(self, request):
        serializer = PasswordResetConfirmSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()

        # Issue a fresh token pair so the user is logged in right away
        refresh = RefreshToken.for_user(user)
        return Response(
            {
                "detail": "Password has been reset successfully.",
                "access": str(refresh.access_token),
                "refresh": str(refresh),
            },
            status=status.HTTP_200_OK,
        )


# ─────────────────────────────────────────────────────────────────────────────
# Change password (authenticated)
# ─────────────────────────────────────────────────────────────────────────────

@extend_schema(tags=["Password"])
class PasswordChangeView(APIView):
    """
    Change the authenticated user's password.

    Requires the current password for confirmation before setting a new one.
    On success, all existing refresh tokens for the user are implicitly
    invalidated (the client must use the new tokens returned in the response).
    """

    permission_classes = (IsAuthenticated,)
    serializer_class = PasswordChangeSerializer

    @extend_schema(
        request=PasswordChangeSerializer,
        responses={
            200: OpenApiResponse(
                description="Password changed. Returns a fresh JWT pair.",
                examples=[
                    OpenApiExample(
                        "Success",
                        value={
                            "detail": "Password changed successfully.",
                            "access": "<new-jwt-access-token>",
                            "refresh": "<new-jwt-refresh-token>",
                        },
                    )
                ],
            ),
            400: OpenApiResponse(description="Current password wrong / new passwords don't match."),
        },
    )
    def post(self, request):
        serializer = PasswordChangeSerializer(
            data=request.data,
            context={"request": request},
        )
        serializer.is_valid(raise_exception=True)
        user = serializer.save()

        # Rotate tokens — old refresh token is now stale since session changed
        refresh = RefreshToken.for_user(user)
        return Response(
            {
                "detail": "Password changed successfully.",
                "access": str(refresh.access_token),
                "refresh": str(refresh),
            },
            status=status.HTTP_200_OK,
        )
    